---
# tasks file for ssmtp

- name: Include distribution specific variables
  include_vars: "{{ ansible_distribution }}.yml"
  tags: ssmtp

- include: CentOS.yml
  when: ansible_distribution == "CentOS"
  tags: ssmtp

- include: Ubuntu.yml
  when: ansible_distribution == "Ubuntu"
  tags: ssmtp

- name: Create sSMTP revaliases file
  template: >
    src=revaliases.j2
    dest=/etc/ssmtp/revaliases
    owner=root
    group=root
    mode=0644
  tags: ssmtp

- name: Create sSMTP configuration file
  template: >
    src=ssmtp.conf.j2
    dest=/etc/ssmtp/ssmtp.conf
    owner=root
    group=root
    mode=0640
  tags: ssmtp
